version: "3.4"
services:
  app:
    image: demo/hello-server
    build: .
    stop_grace_period: 30s
    deploy:
      update_config:
        order: start-first
    environment:
      - VERSION=${VERSION}
    ports:
      - "3000:3000"
